name: 24/7 Professional Nature Stream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          STREAM_URL="https://w1.webcamromania.ro/sboppaltinis2/tracks-v1a1/mono.m3u8"
          STORM_AUDIO="https://actions.google.com/sounds/v1/ambiences/snow_storm.ogg"

          while true; do
            ffmpeg -re -i "$STREAM_URL" -stream_loop -1 -i "$STORM_AUDIO" \
            -filter_complex "[0:v]drawbox=y=0:w=iw:h=45:color=black@1:t=fill[v_box]; \
                             [v_box]drawtext=text='%{localtime\:%Y-%m-%d  %H\\:%M\\:%S}':x=w-350:y=h-60:fontsize=35:fontcolor=white:box=1:boxcolor=black@0.6[v_final]; \
                             [1:a]volume=0.5[a1];[0:a][a1]amix=inputs=2:duration=first[a_final]" \
            -map "[v_final]" -map "[a_final]" \
            -c:v libx264 -preset veryfast -b:v 2500k -pix_fmt yuv420p \
            -c:a aac -b:a 128k -ar 44100 \
            -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}" \
            || sleep 10
          done
